after_failure:
  - mysql -e 'show databases;'
  - cat ./config/database.yml
  - echo $RAILS_ENV
  - bundle exec rake --version
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/initializers/01_mygov.rb.example config/initializers/01_mygov.rb
  - sed -i.bak 's/PUT YOUR SECRET TOKEN HERE/868b2bada3124d10aa96b3793d3e1419e95991c4f4995494e460025d487792effcb17e21bbd3338b4dcf1a250fa693ba52a6a5e3518db9f98f509a446ab48e45/g' config/initializers/01_mygov.rb
  - mysql -e 'create database mygov_test;'
install:
  - bundle install --without development
language: ruby
script: 
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"
services: mysql
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head